Feature/#145751723/restful api endpoints
andela/reaction_commerce_muse pull request #7
Opened 2017-06-06 08:03 UTC by natalie-elizabeth

**Are you submitting to `development`?**

We currently only accept PR's to `development` not `master`

- [ ] Description explains the issue / use-case resolved
- [ ] Only contains code directly related to the issue
- [ ] Has tests.
- [ ] Has docs.
- [ ] Passes all tests
- [ ] Has been linted and follows the style guide

2017-06-06 11:41 UTC, gangachris commented on server/api/endpoints/accounts.js
> +  Api.addRoute("accounts/id", { authRequired: false }, {
`accounts/:id` 🤷‍♂️

2017-06-06 11:44 UTC, gangachris commented on server/api/endpoints/inventory.js
> +      return inventory.findOne().fetch();
`.findOne(id)`

2017-06-06 11:48 UTC, gangachris commented on server/api/endpoints/orders.js
> +      return Orders.findOne().fetch();
ditto: see above comment

2017-06-06 11:48 UTC, gangachris commented on server/api/endpoints/products.js
> +      return Products.findOne().fetch();
ditto: see above comment

2017-06-06 11:50 UTC, gangachris commented on server/api/endpoints/inventory.js
> +      return inventory.findOne().fetch();
.find({_id: this.urlParams.id})
.find({_id: ObjectId(this.urlParams.id)})

or check if `this.urlParams.id` has a value in the first place.

2017-06-07 11:51 UTC, natalie-elizabeth reviewed
I have implemented the changes that were required. This final commit contains all the changes

2017-06-13 11:38 UTC, johnkariuki requested changes

2017-06-13 11:38 UTC, johnkariuki commented on server/api/endpoints/cart.js
> +            statusCode: 200,
Replace the hardcoded http-status codes with this https://www.npmjs.com/package/http-status

2022-02-22 13:52 UTC, closed without merging